Modules/CodeEduBook/Http/routes.php
<?php

Route::group(['middleware' => ['auth', 'isVerified', 'auth.resource']], function () {
    //Rotas de Categorias
    Route::resource('categories', 'CategoriesController', ['except' => 'show']);
    Route::resource('books', 'BooksController', ['except' => 'show']);
    Route::group(['prefix' => 'trashed', 'as' => 'trashed.'], function () {
        Route::resource('books', 'BooksTrashedController', ['only' => ['index', 'show', 'update']]);
    });
});

Modules/CodeEduBook/Models/Book.php
<?php

namespace CodeEduBook\Models;

use ControlUser\Models\User;
use Collective\Html\Eloquent\FormAccessible;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Book extends Model implements Transformable
{
    use TransformableTrait, FormAccessible, SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $fillable = [
        'title',
        'subtitle',
        'price',
        'author_id'
    ];

    public function author()
    {
        return $this->belongsTo(User::class); // Muitos para um
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class)->withTrashed(); //Muitos para Muitos
    }

    public function formCategoriesAttribute()
    {
        return $this->categories()->pluck('id')->all();
    }

}

Modules/CodeEduBook/Http/Controllers/BooksController.php
<?php

namespace CodeEduBook\Http\Controllers;

use CodeEduBook\Http\Requests\BookCreateRequest;
use CodeEduBook\Repositories\BookRepository;
use CodeEduBook\Http\Requests\BookUpdateRequest;
use CodeEduBook\Repositories\CategoryRepository;
use Illuminate\Http\Request;
use ControlUser\Annotations\Mapping as Permission;

/**
 * Class BooksController
 * @package CodeEduBook\Http\Controllers
 * @Permission\Controller(name="book-admin", description="Administração de livros")
 */
class BooksController extends Controller
{
    /**
     * @var BookRepository
     */
    protected $repository;
    /**
     * @var CategoryRepository
     */
    protected $categoryRepository;

    /**
     * BooksController constructor.
     * @param BookRepository $repository
     * @param CategoryRepository $categoryRepository
     */
    public function __construct(BookRepository $repository, CategoryRepository $categoryRepository)
    {
        $this->repository = $repository;
        $this->categoryRepository = $categoryRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @Permission\Action(name="list", description="Ver listagem de livros")
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->get('search');
//        $this->repository->pushCriteria(new FindByTitleCriteria($search));
        $books = $this->repository->paginate();
        //dd($books);
        return view('codeedubook::books.index', compact('books', 'search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @Permission\Action(name="store", description="Criar livro")
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = $this->categoryRepository->lists('name', 'id'); //pluck
        return view('codeedubook::books.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @Permission\Action(name="store", description="Criar livro")
     * @param  \CodeEduBook\Http\Requests\BookCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BookCreateRequest $request)
    {
        $input = $request->all();
        $input['author_id'] = \Auth::user()->id;
        $this->repository->create($input);
        $url = $request->get('redirect_to', route('books.index'));
        $request->session()->flash('message', 'Livro cadastrado com sucesso.');
        return redirect()->to($url);
    }

    /**
     * Display the specified resource.
     *
     * @Permission\Action(name="update", description="Atualizar livro")
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @Permission\Action(name="update", description="Atualizar livro")
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = $this->repository->find($id);
        $this->categoryRepository->withTrashed();
        $categories = $this->categoryRepository->listsWithMutators('name_trashed', 'id'); //pluck
        return view('codeedubook::books.edit', compact('book', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @Permission\Action(name="update", description="Atualizar livro")
     * @param  BookUpdateRequest $request
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function update(BookUpdateRequest $request, $id)
    {
        $input = $request->except(['author_id']);
        $this->repository->update($input, $id);
        $url = $request->get('redirect_to', route('books.index'));
        $request->session()->flash('message', 'Livro alterado com sucesso.');
        return redirect()->to($url);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @Permission\Action(name="destroy", description="Excluir livro")
     * @param $id
     * @return \Illuminate\Http\Response
     * @internal param  Book  $book
     * @internal param int $id
     */
    public function destroy($id)
    {
        $this->repository->delete($id);
        \Session::flash('message', 'Livro excluido com sucesso.');
        return redirect()->to(\URL::previous());
    }
}

Modules/CodeEduBook/resources/views/trashed/books/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Lixeira de livros</h1>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-12">
                {!! Form::model(compact('search'), ['class' => 'form', 'method' => 'GET']) !!}
                <div class="input-group">
                    {!! Form::text('search', null, ['class' => 'form-control', 'placeholder' => 'Pesquisa por título']) !!}
                    <div class="input-group-btn">
                        {!! Button::primary('Buscar')->submit() !!}
                    </div>
                </div>

                {!! Form::close() !!}
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-12">
                @if($books->count() > 0)
                    <table class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th width="4%" class="text-center">ID</th>
                            <th>Titulo</th>
                            <th>Sub-titulo</th>
                            <th>Autor</th>
                            <th>Preço</th>
                            <th width="6%">Ações</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($books as $book)
                            <tr>
                                <td class="text-center">{{ $book->id }}</td>
                                <td>{{ $book->title }}</td>
                                <td>{{ $book->subtitle }}</td>
                                <td>{{ $book->author->name }}</td>
                                <td>{{ $book->price }}</td>
                                <td class="text-center">
                                    <div class="btn-group btn-group-xs">
                                        <a href="{{ route('trashed.books.show', $book->id) }}"
                                           class="btn btn-link">Ver</a>
                                        <?php $deleteForm = "delete-form-{$loop->index}" ?>
                                        <a href="{{ route('trashed.books.update', $book->id) }}" class="btn btn-link"
                                           onclick="event.preventDefault(); document.getElementById('{{$deleteForm}}').submit();">Restaurar</a>
                                        {!! Form::open(['route' => ['trashed.books.update', $book->id], 'id' => $deleteForm, 'style' => 'display:none;', 'method' => 'PUT']) !!}
                                        {!! Form::hidden('redirect_to', URL::previous()) !!}
                                        {!! Form::close() !!}
                                    </div>


                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <span class="text-center center-block">{!! $books->render() !!}</span>
                @else
                    <div class="well">
                        <p class="text-center"><strong>Nenhum livro na lixeira</strong></p>
                    </div>
                @endif
            </div>
        </div>
    </div>

@endsection

Modules/CodeEduBook/resources/views/trashed/books/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3>Livros da lixeira: {{ $book->title }}</h3>
                <ul>
                    <li class="list-group-item"><strong>Titulo</strong></li>
                    <li class="list-group-item">{{ $book->title }}</li>
                    <li class="list-group-item"><strong>Subtitulo</strong></li>
                    <li class="list-group-item">{{$book->subtitle}}</li>
                    <li class="list-group-item"><strong>Preço</strong></li>
                    <li class="list-group-item">{{$book->price}}</li>
                    <li class="list-group-item"><strong>Categorias</strong></li>
                    <li class="list-group-item">{{$book->categories->implode('name_trashed', ', ')}}</li>
                </ul>
            </div>
        </div>
    </div>

@endsection