Modules/ControlUser/Http/routes.php
<?php

Route::group(['as' => 'controluser.', 'middleware' => ['auth', 'isVerified']], function () {
    Route::group(['prefix' => 'admin', 'middleware' => 'auth.resource'], function () {
        Route::resource('users', 'UsersController');
        Route::resource('roles', 'RolesController');
        Route::get('roles/{role}/permissions', 'RolesController@editPermission')->name('roles.permissions.edit');
        Route::put('roles/{role}/permissions', 'RolesController@updatePermission')->name('roles.permissions.update');
    });
    Route::get('users/settings', 'UsersSettingsController@edit')->name('user_settings.edit');
    Route::put('users/settings', 'UsersSettingsController@update')->name('user_settings.update');

    Route::get('email-verification/error', 'UsersConfirmationController@getVerificationError')->name('email-verification.error');
    Route::get('email-verification/check/{token}', 'UsersConfirmationController@getVerification')->name('email-verification.check');
});

Modules/ControlUser/Models/Role.php
<?php

namespace ControlUser\Models;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $fillable = ['name', 'description'];

    public function permissions()
    {
        return $this->belongsToMany(Permission::class);
    }

    public function users()
    {
        return $this->belongsToMany(User::class);
    }
}

Modules/ControlUser/Http/Controllers/RolesController.php
<?php

namespace ControlUser\Http\Controllers;

use ControlUser\Criteria\FindPermissionsGroupCriteria;
use ControlUser\Criteria\FindPermissionsResourceCriteria;
use ControlUser\Http\Requests\PermissionRequest;
use ControlUser\Http\Requests\RoleDeleteRequest;
use ControlUser\Http\Requests\RoleRequest;
use ControlUser\Repositories\PermissionRepository;
use ControlUser\Repositories\RoleRepository;
use Illuminate\Database\QueryException;
use Illuminate\Http\Response;
use ControlUser\Annotations\Mapping as Permission;

/**
 * Class RolesController
 * @package ControlUser\Http\Controllers
 * @Permission\Controller(name="roles-admin", description="Administração de papeis de usuários")
 */
class RolesController extends Controller
{
    /**
     * @var RoleRepository
     */
    private $repository;
    /**
     * @var PermissionRepository
     */
    private $permissionRepository;

    /**
     * RolesController constructor.
     */
    public function __construct(RoleRepository $repository, PermissionRepository $permissionRepository)
    {

        $this->repository = $repository;
        $this->permissionRepository = $permissionRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @Permission\Action(name="list", description="Listar papeis de usuários")
     * @return Response
     */
    public function index()
    {
        $roles = $this->repository->paginate(10);
        return view('controluser::roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @Permission\Action(name="store", description="Criar papeis de usuários")
     * @return Response
     */
    public function create()
    {
        return view('controluser::roles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @Permission\Action(name="store", description="Criar papeis de usuários")
     * @param  RoleRequest $request
     * @return Response
     */
    public function store(RoleRequest $request)
    {
        $this->repository->create($request->all());
        $url = $request->get('redirect_to', route('controluser.roles.index'));
        $request->session()->flash('message', 'Papel de usuário cadastrado com sucesso');
        return redirect()->to($url);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @Permission\Action(name="update", description="Atualizar papel de usuários")
     * @return Response
     */
    public function edit($id)
    {
        $role = $this->repository->find($id);
        return view('controluser::roles.edit', compact('role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @Permission\Action(name="update", description="Atualizar papel de usuários")
     * @param  RoleRequest $request
     * @return Response
     */
    public function update(RoleRequest $request, $id)
    {
        $inputs = $request->except('permissions');
        $this->repository->update($inputs, $id);
        $url = $request->get('redirect_to', route('controluser.roles.index'));
        $request->session()->flash('message', 'Papel de usuário alterado com sucesso');
        return redirect()->to($url);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @Permission\Action(name="destroy", description="Excluir papel de usuários")
     * @return Response
     */
    public function destroy(RoleDeleteRequest $request, $id)
    {
        try{
            $this->repository->delete($id);
            \Session::flash('message', 'Papel de usuário excluido com sucesso');
        }catch (QueryException $ex){
            \Session::flash('error', 'Papel de usuário não pode ser excluido. Ele está relacionado com outros registros.');
        }


        return redirect()->to(\URL::previous());
    }


    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function editPermission($id)
    {
        $this->permissionRepository->pushCriteria(new FindPermissionsResourceCriteria());
        $permissions = $this->permissionRepository->all();
        $this->permissionRepository->resetCriteria();

        $this->permissionRepository->pushCriteria(new FindPermissionsGroupCriteria());
        $permissionsGroup = $this->permissionRepository->all(['name', 'description']);
        $role = $this->repository->find($id);

        return view('controluser::roles.permission', compact('role', 'permissions', 'permissionsGroup'));
    }

    public function updatePermission(PermissionRequest $request, $id)
    {
        $inputs = $request->only('permissions');
        $this->repository->update($inputs, $id);
        $url = $request->get('redirect_to', route('controluser.roles.index'));
        $request->session()->flash('message', 'Permissões atribuidas com sucesso');
        return redirect()->to($url);
    }
}

Modules/ControlUser/resources/views/roles/_form.blade.php
{!! Form::hidden('redirect_to', URL::previous()) !!}
{!! Html::openFormGroup('name', $errors) !!}
    {!! Form::label('name', 'Nome', ['class' => 'control-label']) !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
    {!! Form::error('name', $errors) !!}
{!! Html::closeFormGroup() !!}

{!! Html::openFormGroup('description', $errors) !!}
{!! Form::label('description', 'Descrição', ['class' => 'control-label']) !!}
{!! Form::text('description', null, ['class' => 'form-control']) !!}
{!! Form::error('description', $errors) !!}
{!! Html::closeFormGroup() !!}

Modules/ControlUser/resources/views/roles/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h3>Novo papel de usuário</h3>
            {!! Form::open(['route' => 'controluser.roles.store', 'class' => 'form']) !!}
                @include('controluser::roles._form')
                <div class="form-group">
                    {!! Button::primary('Criar papel de usuário')->submit() !!}
                </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

Modules/ControlUser/resources/views/roles/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h3>Editando usuário</h3>

            {!! Form::model($role, ['method' => 'PUT','route' => ['controluser.roles.update', $role->id], 'class' => 'form']) !!}
            @include('controluser::roles._form')
            <div class="form-group">
                {!! Button::primary('Salvar papel de usuário')->submit() !!}
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

Modules/ControlUser/resources/views/roles/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Listagem de usuários
                    {!! Button::link('<i class="glyphicon glyphicon-plus"></i> Novo papel de usuário')->asLinkTo(route('controluser.roles.create')) !!}
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th width="4%" class="text-center">ID</th>
                        <th>Nome</th>
                        <th>Descrição</th>
                        <th width="8%">Ações</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($roles as $role)
                        <tr>
                            <td class="text-center">{{ $role->id }}</td>
                            <td>{{ $role->name }}</td>
                            <td>{{ $role->description }}</td>
                            <td class="text-center">
                                <div class="btn-group btn-group-xs">
                                    <a href="{{ route('controluser.roles.edit', $role->id) }}" class="btn btn-link"><i class="glyphicon glyphicon-pencil"></i></a>
                                    <?php $deleteForm = "delete-form-{$loop->index}" ?>
                                    <a href="{{ route('controluser.roles.edit', $role->id) }}" class="btn btn-link"
                                       onclick="event.preventDefault(); document.getElementById('{{$deleteForm}}').submit();"><i class="glyphicon glyphicon-trash"></i></a>
                                    {!! Form::open(['route' => ['controluser.roles.destroy', $role->id], 'id' => $deleteForm, 'style' => 'display:none;', 'method' => 'DELETE']) !!}
                                    {!! Form::close() !!}
                                    <a href="{{ route('controluser.roles.permissions.edit', $role->id) }}" class="btn btn-link"><i class="glyphicon glyphicon-cog"></i></a>
                                </div>


                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <span class="text-center center-block">{!! $roles->render() !!}</span>
            </div>
        </div>
    </div>

@endsection

Modules/ControlUser/resources/views/roles/permission.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h3>Permissões de {{ $role->name }}</h3>

            {!! Form::open(['method' => 'PUT','route' => ['controluser.roles.permissions.update', $role->id], 'class' => 'form']) !!}

            <ul class="list-group">
                @foreach($permissionsGroup as $pg)
                    <li class="list-group-item">
                        <h4 class="list-group-item-heading">{{ $pg->description }}</h4>
                        <p class="list-group-item-text">
                        <ul class="list-inline">
                            @php
                                $permissionsSubGroup = $permissions->filter(function ($value) use ($pg){
                                    return $value->name == $pg->name;
                                });
                            @endphp
                            @foreach($permissionsSubGroup as $permission)
                                <li>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="permissions[]"
                                                   {{ $role->permissions->contains('id', $permission->id) ? 'checked="checked"' : '' }} value="{{$permission->id}}">
                                            {{ $permission->resource_description }}
                                        </label>
                                    </div>
                                </li>
                            @endforeach
                        </ul>
                        </p>
                    </li>
                @endforeach
            </ul>

            <div class="form-group">
                {!! Button::primary('Salvar')->submit() !!}
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection