Modules/ControlUser/Http/routes.php
<?php

Route::group(['as' => 'controluser.', 'middleware' => ['auth', 'isVerified']], function () {
    Route::group(['prefix' => 'admin', 'middleware' => 'auth.resource'], function () {
        Route::resource('users', 'UsersController');
        Route::resource('roles', 'RolesController');
        Route::get('roles/{role}/permissions', 'RolesController@editPermission')->name('roles.permissions.edit');
        Route::put('roles/{role}/permissions', 'RolesController@updatePermission')->name('roles.permissions.update');
    });
    Route::get('users/settings', 'UsersSettingsController@edit')->name('user_settings.edit');
    Route::put('users/settings', 'UsersSettingsController@update')->name('user_settings.update');

    Route::get('email-verification/error', 'UsersConfirmationController@getVerificationError')->name('email-verification.error');
    Route::get('email-verification/check/{token}', 'UsersConfirmationController@getVerification')->name('email-verification.check');
});

Modules/ControlUser/Models/User.php
<?php

namespace ControlUser\Models;

use CodeEduBook\Models\Book;
use Collective\Html\Eloquent\FormAccessible;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class User extends Authenticatable implements Transformable
{

    use Notifiable, TransformableTrait, SoftDeletes, FormAccessible;

    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public static function generatePassword($password = null)
    {
        return !$password ? bcrypt(str_random(8)) : bcrypt($password);
    }

    public function books()
    {
        return $this->hasMany(Book::class);
    }

    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    public function formRolesAttribute()
    {
        return $this->roles->pluck('id')->all();
    }

    /**
     * @param Collection|string $role
     * @return boolean
     */
    public function hasRole($role)
    {
        return is_string($role) ?
            $this->roles->contains('name', $role) :
            (boolean) $role->intersect($this->roles)->count();
    }

    public function isAdmin()
    {
        return $this->hasRole(config('controluser.acl.role_admin'));
    }
}

Modules/ControlUser/Http/Controllers/UsersController.php
<?php

namespace ControlUser\Http\Controllers;

use ControlUser\Http\Requests\UserRequest;
use ControlUser\Repositories\RoleRepository;
use ControlUser\Repositories\UserRepository;
use ControlUser\Annotations\Mapping as Permission;


/**
 * Class UsersController
 * @package ControlUser\Http\Controllers
 * @Permission\Controller(name="users-admin", description="Administração de usuários")
 */
class UsersController extends Controller
{
    /**
     * @var \ControlUser\Repositories\UserRepository
     */
    protected $repository;
    /**
     * @var RoleRepository
     */
    private $roleRepository;

    /**
     * UsersController constructor.
     * @param UserRepository $repository
     * @param RoleRepository $roleRepository
     */
    public function __construct(UserRepository $repository, RoleRepository $roleRepository)
    {
        $this->repository = $repository;
        $this->roleRepository = $roleRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @Permission\Action(name="list", description="Ver listagem de usuários")
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = $this->repository->paginate(10);
        return view('controluser::users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @Permission\Action(name="store", description="Criar usuários")
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = $this->roleRepository->all()->pluck('name', 'id');
        return view('controluser::users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @Permission\Action(name="store", description="Criar usuários")
     * @param  UserRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        $this->repository->create($request->all());
        $url = $request->get('redirect_to', route('controluser.users.index'));
        $request->session()->flash('message', 'Usuário cadastrado com sucesso!');
        return redirect()->to($url);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @Permission\Action(name="update", description="Atualizar usuários")
     * @param $id
     * @return \Illuminate\Http\Response
     * @internal param User $user
     * @internal param int $id
     */
    public function edit($id)
    {
        $user = $this->repository->find($id);
        $roles = $this->roleRepository->all()->pluck('name', 'id');
        return view('controluser::users.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @Permission\Action(name="update", description="Atualizar usuários")
     * @param  UserRequest $request
     * @param $id
     * @return \Illuminate\Http\Response
     * @internal param User $user
     * @internal param int $id
     */
    public function update(UserRequest $request, $id)
    {
        $inputs = $request->except(['password']);
        $this->repository->update($inputs, $id);
        $url = $request->get('redirect_to', route('controluser.users.index'));
        $request->session()->flash('message', 'Usuário alterado com sucesso!');
        return redirect()->to($url);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @Permission\Action(name="destroy", description="Excluir usuários")
     * @param $id
     * @return \Illuminate\Http\Response
     * @internal param User $user
     * @internal param int $id
     */
    public function destroy($id)
    {
        $this->repository->delete($id);
        \Session::flash('message', 'Usuário excluido com sucesso!');
        return redirect()->to(\URL::previous());
    }
}

Modules/ControlUser/resources/views/users/_form.blade.php
{!! Form::hidden('redirect_to', URL::previous()) !!}
{!! Html::openFormGroup('name', $errors) !!}
    {!! Form::label('name', 'Nome', ['class' => 'control-label']) !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
    {!! Form::error('name', $errors) !!}
{!! Html::closeFormGroup() !!}

{!! Html::openFormGroup('email', $errors) !!}
{!! Form::label('email', 'E-mail', ['class' => 'control-label']) !!}
{!! Form::text('email', null, ['class' => 'form-control']) !!}
{!! Form::error('email', $errors) !!}
{!! Html::closeFormGroup() !!}

{!! Html::openFormGroup('roles.*', $errors) !!}
{!! Form::label('roles[]', 'Papel de usuário', ['class' => 'control-label']) !!}
{!! Form::select('roles[]', $roles, null, ['class' => 'form-control', 'multiple' => true]) !!}
{!! Form::error('roles.*', $errors) !!}
{!! Html::closeFormGroup() !!}

Modules/ControlUser/resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h3>Novo usuário</h3>
            {!! Form::open(['route' => 'controluser.users.store', 'class' => 'form']) !!}
                @include('controluser::users._form')
                <div class="form-group">
                    {!! Button::primary('Criar Usuário')->submit() !!}
                </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

Modules/ControlUser/resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h3>Editando usuário</h3>

            {!! Form::model($user, ['method' => 'PUT','route' => ['controluser.users.update', $user->id], 'class' => 'form']) !!}
            @include('controluser::users._form')
            <div class="form-group">
                {!! Button::primary('Salvar Usuário')->submit() !!}
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

Modules/ControlUser/resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Listagem de usuários
                    {!! Button::link('<i class="glyphicon glyphicon-plus"></i> Novo Usuário')->asLinkTo(route('controluser.users.create')) !!}
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th width="4%" class="text-center">ID</th>
                        <th>Nome</th>
                        <th>E-mail</th>
                        <th>Roles</th>
                        <th width="6%">Ações</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td class="text-center">{{ $user->id }}</td>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->roles->implode('name', ' | ') }}</td>
                            <td class="text-center">
                                <div class="btn-group btn-group-xs">
                                    <a href="{{ route('controluser.users.edit', $user->id) }}" class="btn btn-link"><i
                                                class="glyphicon glyphicon-pencil"></i></a>

                                    @if($user->id == \Auth::user()->id)
                                        <a href="#" class="btn btn-link text-danger disabled">
                                            <i class="glyphicon glyphicon-trash"></i>
                                        </a>
                                    @else
                                        <?php $deleteForm = "delete-form-{$loop->index}" ?>
                                        <a href="{{ route('controluser.users.edit', $user->id) }}" class="btn btn-link"
                                           onclick="event.preventDefault(); document.getElementById('{{$deleteForm}}').submit();">
                                            <i class="glyphicon glyphicon-trash"></i>
                                        </a>
                                        {!! Form::open(['route' => ['controluser.users.destroy', $user->id], 'id' => $deleteForm, 'style' => 'display:none;', 'method' => 'DELETE']) !!}
                                        {!! Form::close() !!}
                                    @endif
                                </div>


                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <span class="text-center center-block">{!! $users->render() !!}</span>
            </div>
        </div>
    </div>

@endsection